spring.application.name=Gold_Wallet

# Database connection
spring.datasource.url=jdbc:mysql://172.16.161.134:3306/digitalgoldwallet
spring.datasource.username=user1
spring.datasource.password=1234

# MySQL driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect